In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics



In [7]:
df=pd.read_csv('studi_num.csv')
df

JURUSAN  GENDER  ASAL_SEKOLAH  RERATA_SKS  ASISTEN  LAMA_STUDI
0         1       1             1           1        1           1
1         1       1             1           1        1           1
2         1       1             1           1        1           1
3         2       2             1           1        1           1
4         2       2             2           1        1           1
5         2       1             2           1        1           1
6         2       1             1           1        2           2
7         1       1             1           2        1           1
8         1       2             1           2        1           1
9         2       1             1           1        2           2
10        3       1             1           1        1           1
11        2       1             2           2        1           1
12        2       2             1           2        1           2

In [8]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 5].values


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [10]:
from sklearn.naive_bayes import GaussianNB

In [11]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [12]:
y_pred = model.predict(X_test)


In [14]:
y_pred

array([1, 2, 1, 1], dtype=int64)

In [19]:
np.array(y_test)

array([1, 1, 1, 1], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3, 1],
       [0, 0]], dtype=int64)

In [23]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.75


In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      0.75      0.86         4
           2       0.00      0.00      0.00         0

    accuracy                           0.75         4
   macro avg       0.50      0.38      0.43         4
weighted avg       1.00      0.75      0.86         4



C:\Users\Asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
